# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 12:16
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=200)),
                ('phoneno', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('activated', models.BooleanField(default=False)),
                ('judge', models.BooleanField(default=False)),
                ('college', models.BooleanField(default=False)),
                ('club', models.BooleanField(default=False)),
                ('about', models.CharField(blank=True, default='', max_length=500)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('experience', models.PositiveSmallIntegerField(default=0)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('profile_picture', models.ImageField(blank=True, default='default/new_logo.png', null=True, upload_to=users.models.upload_loction)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='clubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('college', models.CharField(default='', max_length=150)),
                ('admin_name', models.CharField(default='', max_length=100)),
                ('club_email', models.CharField(default='', max_length=100, unique=True)),
                ('phone', models.CharField(default='', max_length=10)),
                ('video', models.CharField(default='', max_length=250)),
                ('website', models.CharField(default='', max_length=250)),
                ('about', models.CharField(default='', max_length=1000)),
                ('logo', models.ImageField(blank=True, default='default/club_default.jpg', null=True, upload_to=users.models.upload_loction)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='event_registered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('live', models.BooleanField(default=False)),
                ('registration', models.BooleanField(default=False)),
                ('about', models.CharField(default='', max_length=1000)),
                ('website', models.CharField(default='', max_length=250)),
                ('logo', models.ImageField(blank=True, default='default/club_default.jpg', null=True, upload_to=users.models.upload_loction)),
                ('inter_type', models.BooleanField(default=False)),
                ('marketing', models.BooleanField(default=False)),
                ('team_size1', models.IntegerField(default=1)),
                ('finance', models.BooleanField(default=False)),
                ('team_size2', models.IntegerField(default=1)),
                ('public_relations', models.BooleanField(default=False)),
                ('team_size3', models.IntegerField(default=1)),
                ('human_resources', models.BooleanField(default=False)),
                ('team_size4', models.IntegerField(default=1)),
                ('ent_dev', models.BooleanField(default=False)),
                ('team_size5', models.IntegerField(default=1)),
                ('best_manager', models.BooleanField(default=False)),
                ('team_size6', models.IntegerField(default=1)),
                ('current', models.BooleanField(default=False)),
                ('email', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.clubs')),
            ],
        ),
        migrations.CreateModel(
            name='follow_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='register_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='room_judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_email', models.CharField(default='', max_length=100)),
                ('judge_password', models.CharField(default='', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='round_room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='round_scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.IntegerField(blank=True, default=0, null=True)),
                ('question2', models.IntegerField(blank=True, default=0, null=True)),
                ('question3', models.IntegerField(blank=True, default=0, null=True)),
                ('question4', models.IntegerField(blank=True, default=0, null=True)),
                ('question5', models.IntegerField(blank=True, default=0, null=True)),
                ('creativity', models.IntegerField(blank=True, default=0, null=True)),
                ('content', models.IntegerField(blank=True, default=0, null=True)),
                ('presentation', models.IntegerField(blank=True, default=0, null=True)),
                ('rebuttal', models.IntegerField(blank=True, default=0, null=True)),
                ('communication', models.IntegerField(blank=True, default=0, null=True)),
                ('feasibility', models.IntegerField(blank=True, default=0, null=True)),
                ('feedback', models.CharField(default='', max_length=1000)),
                ('submitted', models.BooleanField(default=False)),
                ('data1', models.FileField(null=True, upload_to=users.models.upload_loction)),
                ('data2', models.FileField(null=True, upload_to=users.models.upload_loction)),
                ('data3', models.FileField(null=True, upload_to=users.models.upload_loction)),
            ],
        ),
        migrations.CreateModel(
            name='rounds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_judge', models.BooleanField(default=False)),
                ('title', models.CharField(default='', max_length=150)),
                ('sub_title', models.CharField(default='', max_length=150)),
                ('about', models.CharField(default='', max_length=1000)),
                ('task1', models.CharField(default='', max_length=150)),
                ('task2', models.CharField(blank=True, default='', max_length=150)),
                ('tast3', models.CharField(blank=True, default='', max_length=150)),
                ('task4', models.CharField(blank=True, default='', max_length=150)),
                ('task5', models.CharField(blank=True, default='', max_length=150)),
                ('resource1', models.CharField(default='', max_length=150)),
                ('resource2', models.CharField(blank=True, default='', max_length=150)),
                ('resource3', models.CharField(blank=True, default='', max_length=150)),
                ('resource4', models.CharField(blank=True, default='', max_length=150)),
                ('resource5', models.CharField(blank=True, default='', max_length=150)),
                ('creativity', models.BooleanField(default=False)),
                ('content', models.BooleanField(default=False)),
                ('presentation', models.BooleanField(default=False)),
                ('rebuttal', models.BooleanField(default=False)),
                ('communication', models.BooleanField(default=False)),
                ('feasibility', models.BooleanField(default=False)),
                ('feedback', models.BooleanField(default=False)),
                ('question1', models.CharField(default='', max_length=150)),
                ('question2', models.CharField(blank=True, default='', max_length=150)),
                ('question3', models.CharField(blank=True, default='', max_length=150)),
                ('question4', models.CharField(blank=True, default='', max_length=150)),
                ('question5', models.CharField(blank=True, default='', max_length=150)),
                ('type', models.IntegerField(default=0)),
                ('created', models.DateField(default=datetime.date.today)),
                ('published', models.BooleanField(default=False)),
                ('team_size', models.IntegerField(default=1)),
                ('deadline', models.DateField(default=None, null=True)),
                ('email', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.events')),
            ],
        ),
        migrations.CreateModel(
            name='student_scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creativity', models.IntegerField(default=0)),
                ('content', models.IntegerField(default=0)),
                ('presentation', models.IntegerField(default=0)),
                ('rebuttal', models.IntegerField(default=0)),
                ('communication', models.IntegerField(default=0)),
                ('feasibility', models.IntegerField(default=0)),
                ('feedback', models.CharField(default='', max_length=1000)),
                ('question1', models.IntegerField(default=0)),
                ('question2', models.IntegerField(blank=True, default=0)),
                ('question3', models.IntegerField(blank=True, default=0)),
                ('question4', models.IntegerField(blank=True, default=0)),
                ('question5', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='colleges',
            fields=[
                ('email', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.CharField(default='', max_length=350)),
                ('college_name', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='interests',
            fields=[
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('label', models.CharField(default='', max_length=50)),
                ('marketing', models.BooleanField(default=False)),
                ('finance', models.BooleanField(default=False)),
                ('public_relations', models.BooleanField(default=False)),
                ('human_resources', models.BooleanField(default=False)),
                ('ent_dev', models.BooleanField(default=False)),
                ('business_quiz', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='judge_detail',
            fields=[
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='student_detail',
            fields=[
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('label', models.CharField(default='', max_length=50)),
                ('degree', models.CharField(default='', max_length=100)),
                ('college', models.CharField(default='', max_length=150)),
                ('year', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third')], default='First', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='student_scores',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='round_scores',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_score', to='users.rounds'),
        ),
        migrations.AddField(
            model_name='round_scores',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='round_room',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.rounds'),
        ),
        migrations.AddField(
            model_name='room_judge',
            name='room',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.round_room'),
        ),
        migrations.AddField(
            model_name='room_judge',
            name='round',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.rounds'),
        ),
        migrations.AddField(
            model_name='register_table',
            name='current_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='register_table',
            name='registered_to',
            field=models.ManyToManyField(to='users.clubs'),
        ),
        migrations.AddField(
            model_name='follow_table',
            name='connected_to',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follow_table',
            name='current_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event_registered',
            name='current_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event_registered',
            name='registered_to',
            field=models.ManyToManyField(to='users.events'),
        ),
        migrations.AddField(
            model_name='clubs',
            name='email',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.colleges'),
        ),
    ]
