# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-28 04:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='round_scores',
            name='submission_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
