# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-23 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='event',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='member1',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='member2',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='member3',
        ),
        migrations.RemoveField(
            model_name='interests',
            name='rcode',
        ),
        migrations.DeleteModel(
            name='teams',
        ),
    ]
