# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-14 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170511_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='name',
            field=models.CharField(default='Dummy', max_length=100),
        ),
    ]
