# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-23 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170623_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='interests',
            name='rcode',
            field=models.BooleanField(default=False),
        ),
    ]
