# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170516_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round_scores',
            name='feedback',
            field=models.CharField(default='Not Available', max_length=1000, null=True),
        ),
    ]
