# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-09 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170803_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='bmlabel',
            field=models.CharField(default='Best Manager', max_length=20),
        ),
        migrations.AddField(
            model_name='events',
            name='cslabel',
            field=models.CharField(default='Corporate Strategy', max_length=20),
        ),
        migrations.AddField(
            model_name='events',
            name='edlabel',
            field=models.CharField(default='Entrepreneurship Development', max_length=20),
        ),
        migrations.AddField(
            model_name='events',
            name='finlabel',
            field=models.CharField(default='Finance', max_length=20),
        ),
        migrations.AddField(
            model_name='events',
            name='hrlabel',
            field=models.CharField(default='Human Resource', max_length=20),
        ),
        migrations.AddField(
            model_name='events',
            name='mktlabel',
            field=models.CharField(default='Marketing', max_length=20),
        ),
        migrations.AddField(
            model_name='events',
            name='prlabel',
            field=models.CharField(default='Public Relations', max_length=20),
        ),
        migrations.AddField(
            model_name='events',
            name='qulabel',
            field=models.CharField(default='Quiz', max_length=20),
        ),
        migrations.AddField(
            model_name='events',
            name='telabel',
            field=models.CharField(default='Team', max_length=20),
        ),
    ]
