# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-10 12:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170809_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='member1',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='member2',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='member3',
        ),
        migrations.AddField(
            model_name='teams',
            name='club',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.clubs'),
        ),
        migrations.AddField(
            model_name='teams',
            name='student',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
