# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 20:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170516_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round_scores',
            name='round',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='round_score', to='users.rounds'),
        ),
        migrations.AlterField(
            model_name='round_scores',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
