# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-23 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170623_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
