# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-10 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170810_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teams',
            old_name='rcode',
            new_name='tcode',
        ),
    ]
