# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-23 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170624_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colleges',
            name='logo',
            field=models.ImageField(blank=True, default='default/new_logo.png', null=True, upload_to=users.models.upload_loction_college),
        ),
    ]
