# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170516_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='round_scores',
            name='judged',
            field=models.BooleanField(default=False),
        ),
    ]
