# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-24 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170624_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rounds',
            name='about',
            field=models.CharField(blank=True, default='', max_length=2500),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='core1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='core2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='core3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='core4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='core5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='resource1data',
            field=models.FileField(blank=True, null=True, upload_to=users.models.case_data),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='resource2data',
            field=models.FileField(blank=True, null=True, upload_to=users.models.case_data),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='resource3data',
            field=models.FileField(blank=True, null=True, upload_to=users.models.case_data),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='resource4data',
            field=models.FileField(blank=True, null=True, upload_to=users.models.case_data),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='resource5data',
            field=models.FileField(blank=True, null=True, upload_to=users.models.case_data),
        ),
    ]
