# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-12 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170810_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colleges',
            name='college_name',
            field=models.CharField(choices=[('Christ University B.COM', 'Christ University B.COM'), ('Christ University D.M.S', 'Christ University D.M.S'), ('Christ University D.P.S', 'Christ University D.P.S'), ('Christ University, Bannerghatta', 'Christ University, Bannerghatta'), ('Jain University SCS', 'Jain University SCS'), ('Jain University CMS', 'Jain University CMS'), ('Mount Carmel B.COM', 'Mount Carmel B.COM'), ('Mount Carmel BBA', 'Mount Carmel BBA'), ('St.Josephs B.COM', 'St.Josephs B.COM'), ('Kristu Jayanti College B.COM', 'Kristu Jayanti College  B.COM'), ('Kristu Jayanti College BBA', 'Kristu Jayanti College BBA'), ('KLE CBALC Belgaum', 'KLE CBALC Belgaum'), ('Bishop Cotton Womens College', 'Bishop Cotton Womens College'), ('Garden City College', 'Garden City College'), ('Trinity College of Commerce', 'Trinity College of Commerce'), ('Manipal University DOC', 'Manipal University DOC'), ('Vidhyaashram FGC', 'Vidhyaashram FGC')], default='', max_length=200),
        ),
    ]
