# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_round_scores_judged'),
    ]

    operations = [
        migrations.AddField(
            model_name='round_scores',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
