# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-24 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20170624_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rounds',
            name='about',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
    ]
