# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-16 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20170815_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='round_scores',
            name='judged_value',
            field=models.IntegerField(default=0),
        ),
    ]
