# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-18 20:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20170516_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_registered_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core1', models.BooleanField(default=0)),
                ('core2', models.BooleanField(default=0)),
                ('core3', models.BooleanField(default=0)),
                ('core4', models.BooleanField(default=0)),
                ('core5', models.BooleanField(default=0)),
                ('core6', models.BooleanField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.events')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
