# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-16 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_round_scores_judged_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round_scores',
            name='communication',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='round_scores',
            name='content',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='round_scores',
            name='creativity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='round_scores',
            name='feasibility',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='round_scores',
            name='presentation',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='round_scores',
            name='question1',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='round_scores',
            name='question2',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='round_scores',
            name='question3',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='round_scores',
            name='question4',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='round_scores',
            name='question5',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='round_scores',
            name='rebuttal',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
