# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-25 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20170624_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_registered_details',
            name='bmttotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event_registered_details',
            name='edtotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event_registered_details',
            name='fintotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event_registered_details',
            name='hrttotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event_registered_details',
            name='mkttotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event_registered_details',
            name='prtotal',
            field=models.IntegerField(default=0),
        ),
    ]
