# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-18 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_event_registered_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_registered_details',
            name='teammate1',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='event_registered_details',
            name='teammate2',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='event_registered_details',
            name='teammate3',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
