# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-25 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20170626_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rounds',
            name='offline',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
