# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-25 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20170626_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rounds',
            name='question1',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='question2',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='question3',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='question4',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='question5',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
