# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rounds_qualified'),
    ]

    operations = [
        migrations.AddField(
            model_name='round_scores',
            name='qualified',
            field=models.BooleanField(default=False),
        ),
    ]
