# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-25 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20170626_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rounds',
            name='core1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='core2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='core3',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='core4',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='core5',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
