# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_round_scores_qualified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round_scores',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_score', to='users.rounds'),
        ),
    ]
