# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-25 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20170626_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='rounds',
            name='max_score',
            field=models.IntegerField(default=100),
        ),
    ]
