# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-26 03:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rounds_max_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_registered_details',
            old_name='bmttotal',
            new_name='bmtotal',
        ),
        migrations.RenameField(
            model_name='event_registered_details',
            old_name='hrttotal',
            new_name='hrtotal',
        ),
    ]
