# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-21 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_rounds_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='rounds',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
