# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-26 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20170626_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round_scores',
            name='qualified',
            field=models.BooleanField(default=True),
        ),
    ]
