# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20170521_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='rounds',
            name='club',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.clubs'),
        ),
    ]
