# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20170329_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='location',
            field=models.CharField(default='', max_length=500),
        ),
    ]
