# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_rounds_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='rounds',
            name='enddate',
            field=models.DateField(default=None, null=True),
        ),
    ]
