# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_sub_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_detail',
            name='section',
            field=models.CharField(default='', max_length=10),
        ),
    ]
