# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 18:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_remove_student_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
