# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_events_multiregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='multiregistration',
            field=models.BooleanField(default=False),
        ),
    ]
