# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20170404_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_detail',
            name='label',
            field=models.CharField(default='', max_length=50),
        ),
    ]
