# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20170530_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='rounds',
            name='core1',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='rounds',
            name='core2',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='rounds',
            name='core3',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='rounds',
            name='core4',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='rounds',
            name='core5',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='student_detail',
            name='year',
            field=models.CharField(choices=[('First', 'Right'), ('Left', 'Second'), ('Third', 'Third')], default='First', max_length=10),
        ),
    ]
