# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20170530_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rounds',
            name='core1',
            field=models.IntegerField(choices=[(1, 'Marketing'), (2, 'Finance'), (3, 'Public Relations'), (4, 'Human Resources'), (5, 'Entrpreneur and Development'), (6, 'Best Manager')], default=8),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='core2',
            field=models.IntegerField(choices=[(1, 'Marketing'), (2, 'Finance'), (3, 'Public Relations'), (4, 'Human Resources'), (5, 'Entrpreneur and Development'), (6, 'Best Manager')], default=8),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='core3',
            field=models.IntegerField(choices=[(1, 'Marketing'), (2, 'Finance'), (3, 'Public Relations'), (4, 'Human Resources'), (5, 'Entrpreneur and Development'), (6, 'Best Manager')], default=8),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='core4',
            field=models.IntegerField(choices=[(1, 'Marketing'), (2, 'Finance'), (3, 'Public Relations'), (4, 'Human Resources'), (5, 'Entrpreneur and Development'), (6, 'Best Manager')], default=8),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='core5',
            field=models.IntegerField(choices=[(1, 'Marketing'), (2, 'Finance'), (3, 'Public Relations'), (4, 'Human Resources'), (5, 'Entrpreneur and Development'), (6, 'Best Manager')], default=8),
        ),
        migrations.AlterField(
            model_name='student_detail',
            name='year',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third')], default='First', max_length=10),
        ),
    ]
