# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_student_detail_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='interests',
            name='label',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='judge_detail',
            name='label',
            field=models.CharField(default='', max_length=50),
        ),
    ]
