# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20170404_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge_detail',
            name='college',
            field=models.CharField(default='', max_length=150),
        ),
    ]
