# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_judge_detail_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge_detail',
            name='website',
            field=models.URLField(default=''),
        ),
    ]
