# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20170530_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='about',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='events',
            name='about',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='events',
            name='quota11',
            field=models.IntegerField(default=400),
        ),
        migrations.AlterField(
            model_name='events',
            name='quota12',
            field=models.IntegerField(default=400),
        ),
        migrations.AlterField(
            model_name='events',
            name='quota13',
            field=models.IntegerField(default=400),
        ),
        migrations.AlterField(
            model_name='events',
            name='quota21',
            field=models.IntegerField(default=400),
        ),
        migrations.AlterField(
            model_name='events',
            name='quota22',
            field=models.IntegerField(default=400),
        ),
        migrations.AlterField(
            model_name='events',
            name='quota23',
            field=models.IntegerField(default=400),
        ),
        migrations.AlterField(
            model_name='events',
            name='quota31',
            field=models.IntegerField(default=400),
        ),
        migrations.AlterField(
            model_name='events',
            name='quota32',
            field=models.IntegerField(default=400),
        ),
        migrations.AlterField(
            model_name='events',
            name='quota33',
            field=models.IntegerField(default=400),
        ),
        migrations.AlterField(
            model_name='events',
            name='quota41',
            field=models.IntegerField(default=400),
        ),
        migrations.AlterField(
            model_name='events',
            name='quota42',
            field=models.IntegerField(default=400),
        ),
        migrations.AlterField(
            model_name='events',
            name='quota43',
            field=models.IntegerField(default=400),
        ),
        migrations.AlterField(
            model_name='events',
            name='quota51',
            field=models.IntegerField(default=400),
        ),
        migrations.AlterField(
            model_name='events',
            name='quota52',
            field=models.IntegerField(default=400),
        ),
        migrations.AlterField(
            model_name='events',
            name='quota53',
            field=models.IntegerField(default=400),
        ),
        migrations.AlterField(
            model_name='events',
            name='quota61',
            field=models.IntegerField(default=400),
        ),
        migrations.AlterField(
            model_name='events',
            name='quota62',
            field=models.IntegerField(default=400),
        ),
        migrations.AlterField(
            model_name='events',
            name='quota63',
            field=models.IntegerField(default=400),
        ),
        migrations.AlterField(
            model_name='round_scores',
            name='feedback',
            field=models.CharField(default='Not Available', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='about',
            field=models.CharField(default='', max_length=400),
        ),
    ]
