# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20170608_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_detail',
            name='year',
            field=models.CharField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third')], default='First', max_length=10),
        ),
    ]
