# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 13:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20170404_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubs',
            old_name='club_name',
            new_name='admin_name',
        ),
        migrations.RemoveField(
            model_name='colleges',
            name='college_email',
        ),
        migrations.RemoveField(
            model_name='colleges',
            name='college_number',
        ),
        migrations.RemoveField(
            model_name='colleges',
            name='id',
        ),
        migrations.AddField(
            model_name='clubs',
            name='club_email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='clubs',
            name='club_password',
            field=models.CharField(default='practrdefault', max_length=100),
        ),
        migrations.AddField(
            model_name='clubs',
            name='email',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.colleges'),
        ),
        migrations.AddField(
            model_name='clubs',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='colleges',
            name='address',
            field=models.CharField(default='', max_length=350),
        ),
        migrations.AddField(
            model_name='colleges',
            name='email',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='colleges',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='club',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='college',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='colleges',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
