# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20170608_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='registered11',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='events',
            name='registered12',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='events',
            name='registered13',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='events',
            name='registered21',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='events',
            name='registered22',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='events',
            name='registered23',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='events',
            name='registered31',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='events',
            name='registered32',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='events',
            name='registered33',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='events',
            name='registered41',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='events',
            name='registered42',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='events',
            name='registered43',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='events',
            name='registered51',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='events',
            name='registered52',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='events',
            name='registered53',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='events',
            name='registered61',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='events',
            name='registered62',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='events',
            name='registered63',
            field=models.IntegerField(default=0),
        ),
    ]
