# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20170404_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubs',
            name='club_password',
        ),
    ]
