# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_remove_clubs_club_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colleges',
            old_name='name',
            new_name='college_name',
        ),
    ]
