# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20170608_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judge_detail',
            name='round',
        ),
        migrations.AddField(
            model_name='judge_detail',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
