# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20170609_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge_detail',
            name='club',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.clubs'),
        ),
    ]
