# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20170404_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('registraion', models.BooleanField(default=False)),
                ('email', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.clubs')),
            ],
        ),
    ]
