# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='registraion',
            new_name='registration',
        ),
        migrations.AlterField(
            model_name='clubs',
            name='club_email',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
