# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20170406_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='about',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='clubs',
            name='video',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='clubs',
            name='website',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='events',
            name='about',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
