# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_rounds_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_detail',
            name='year',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third')], default='First', max_length=10),
        ),
    ]
