# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 18:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20170407_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='link',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
