# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20170609_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='rounds',
            name='offline',
            field=models.BooleanField(default=False),
        ),
    ]
