# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_clubs_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubs',
            name='link',
        ),
    ]
