# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_rounds_offline'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='subhead1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='subhead2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='subhead3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='subhead4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='subhead5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='subhead6',
            field=models.BooleanField(default=False),
        ),
    ]
