# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20170609_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='colleges',
            name='logo',
            field=models.ImageField(blank=True, default='default/new_logo.png', null=True, upload_to=users.models.upload_loction),
        ),
        migrations.AlterField(
            model_name='events',
            name='current',
            field=models.BooleanField(default=True),
        ),
    ]
