# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_remove_clubs_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='video',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='website',
            field=models.CharField(default='', max_length=250),
        ),
    ]
