# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_auto_20170408_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='website',
            field=models.CharField(default='', max_length=250),
        ),
    ]
