# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_events_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='rounds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(default='', max_length=150)),
                ('club', models.CharField(default='', max_length=150)),
                ('ext_judge', models.BooleanField(default=False)),
                ('title', models.CharField(default='', max_length=150)),
                ('sub_title', models.CharField(default='', max_length=150)),
                ('about', models.CharField(default='', max_length=1000)),
                ('task1', models.CharField(default='', max_length=150)),
                ('task2', models.CharField(default='', max_length=150)),
                ('tast3', models.CharField(default='', max_length=150)),
                ('task4', models.CharField(default='', max_length=150)),
                ('task5', models.CharField(default='', max_length=150)),
                ('resource1', models.CharField(default='', max_length=150)),
                ('resource2', models.CharField(default='', max_length=150)),
                ('resource3', models.CharField(default='', max_length=150)),
                ('resource4', models.CharField(default='', max_length=150)),
                ('resource5', models.CharField(default='', max_length=150)),
                ('creativity', models.BooleanField(default=False)),
                ('content', models.BooleanField(default=False)),
                ('presentation', models.BooleanField(default=False)),
                ('rebuttal', models.BooleanField(default=False)),
                ('communication', models.BooleanField(default=False)),
                ('feasibility', models.BooleanField(default=False)),
                ('feedback', models.BooleanField(default=False)),
                ('question1', models.CharField(default='', max_length=150)),
                ('question2', models.CharField(default='', max_length=150)),
                ('question3', models.CharField(default='', max_length=150)),
                ('question4', models.CharField(default='', max_length=150)),
                ('question5', models.CharField(default='', max_length=150)),
                ('email', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.events')),
            ],
        ),
    ]
