# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_auto_20170609_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='location',
            field=models.CharField(blank=True, choices=[('Bangalore', 'Bangalore'), ('Mysore', 'Mysore')], default='', max_length=100),
        ),
    ]
