# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_auto_20170411_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='inter_type',
            field=models.BooleanField(default=False),
        ),
    ]
