# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-10 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_auto_20170611_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rounds',
            name='about',
            field=models.CharField(default='', max_length=400),
        ),
    ]
