# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_follow_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow_table',
            old_name='user',
            new_name='users',
        ),
    ]
