# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_auto_20170414_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow_table',
            old_name='users',
            new_name='connected_to',
        ),
    ]
