# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_auto_20170414_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow_table',
            name='connected_to',
        ),
        migrations.RemoveField(
            model_name='follow_table',
            name='current_user',
        ),
        migrations.AddField(
            model_name='follow_table',
            name='asad',
            field=models.CharField(default='', max_length=223),
        ),
    ]
