# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-11 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_auto_20170612_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rounds',
            name='deadline',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
