# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-12 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_auto_20170612_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rounds',
            name='resource1data',
            field=models.FileField(blank=True, null=True, upload_to=users.models.round_data),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='resource2data',
            field=models.FileField(blank=True, null=True, upload_to=users.models.round_data),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='resource3data',
            field=models.FileField(blank=True, null=True, upload_to=users.models.round_data),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='resource4data',
            field=models.FileField(blank=True, null=True, upload_to=users.models.round_data),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='resource5data',
            field=models.FileField(blank=True, null=True, upload_to=users.models.round_data),
        ),
    ]
