# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_auto_20170414_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow_table',
            name='added',
            field=models.BooleanField(default=False),
        ),
    ]
