# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_auto_20170612_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_registered_details',
            name='rcode',
            field=models.IntegerField(default=0),
        ),
    ]
