# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_follow_table_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_scores',
            old_name='creativiy',
            new_name='communication',
        ),
        migrations.RenameField(
            model_name='student_scores',
            old_name='overall',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='follow_table',
            name='added',
        ),
        migrations.AddField(
            model_name='student_scores',
            name='creativity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student_scores',
            name='feasibility',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student_scores',
            name='feedback',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='student_scores',
            name='question1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student_scores',
            name='question2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='student_scores',
            name='question3',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='student_scores',
            name='question4',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='student_scores',
            name='question5',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='student_scores',
            name='rebuttal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='events',
            name='logo',
            field=models.ImageField(blank=True, default='/CSE Race/Wallpaper.jpg', null=True, upload_to=users.models.upload_loction),
        ),
    ]
