# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_auto_20170414_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.upload_loction),
        ),
    ]
