# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_events_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='prefix',
            field=models.CharField(blank=True, default='', max_length=4, null=True),
        ),
    ]
