# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_auto_20170613_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_registered_details',
            name='rcode',
            field=models.CharField(default='', max_length=10),
        ),
    ]
