# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 10:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_auto_20170415_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_detail',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
