# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_auto_20170613_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='round_scores',
            name='rcode',
            field=models.CharField(default='', max_length=10),
        ),
    ]
