# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_clubs_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default/new_logo', null=True, upload_to=users.models.upload_loction),
        ),
    ]
