# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-15 00:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_round_scores_rcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='rcode',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='judge_detail',
            name='college',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='judge_detail',
            name='degree',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='judge_detail',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='judge_detail',
            name='website',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='member3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member3', to=settings.AUTH_USER_MODEL),
        ),
    ]
