# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-15 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_auto_20170615_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rounds',
            name='about',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='question1',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='resource1',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='task1',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
