# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-15 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_auto_20170615_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rounds',
            name='ext_judge',
        ),
        migrations.AlterField(
            model_name='rounds',
            name='sub_title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
