# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-15 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_rounds_ext_judge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rounds',
            name='core1',
            field=models.IntegerField(choices=[(1, 'Marketing'), (2, 'Finance'), (3, 'Public Relations'), (4, 'Human Resources'), (5, 'Entrpreneur and Development'), (6, 'Best Manager')], default=1),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='core2',
            field=models.IntegerField(choices=[(1, 'Marketing'), (2, 'Finance'), (3, 'Public Relations'), (4, 'Human Resources'), (5, 'Entrpreneur and Development'), (6, 'Best Manager')], default=1),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='core3',
            field=models.IntegerField(choices=[(1, 'Marketing'), (2, 'Finance'), (3, 'Public Relations'), (4, 'Human Resources'), (5, 'Entrpreneur and Development'), (6, 'Best Manager')], default=1),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='core4',
            field=models.IntegerField(choices=[(1, 'Marketing'), (2, 'Finance'), (3, 'Public Relations'), (4, 'Human Resources'), (5, 'Entrpreneur and Development'), (6, 'Best Manager')], default=1),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='core5',
            field=models.IntegerField(choices=[(1, 'Marketing'), (2, 'Finance'), (3, 'Public Relations'), (4, 'Human Resources'), (5, 'Entrpreneur and Development'), (6, 'Best Manager')], default=1),
        ),
    ]
