# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_register_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='logo',
            field=models.ImageField(blank=True, default='default/club_default.jpg', null=True, upload_to=users.models.upload_loction),
        ),
    ]
