# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_auto_20170418_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='logo',
            field=models.ImageField(blank=True, default='default/new_logo.png', null=True, upload_to=users.models.upload_loction),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default/new_logo.png', null=True, upload_to=users.models.upload_loction),
        ),
    ]
