# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_events_team_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_table',
            name='registered_to',
            field=models.ManyToManyField(to='users.clubs'),
        ),
    ]
