# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0066_auto_20170418_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='business_quiz',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='ent_dev',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='finance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='human_resources',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='marketing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='public_relations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rounds',
            name='type',
            field=models.CharField(choices=[('Marketing', 'Marketing'), ('Finance', 'Finance'), ('Public_Relations', 'Public_Relations'), ('Human_Resources', 'Human_Resources'), ('ent_dev', 'ent_dev'), ('business_quiz', 'business_quiz')], default=None, max_length=20),
        ),
    ]
