# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_auto_20170420_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='logo',
            field=models.ImageField(blank=True, default='default/club_default.jpg', null=True, upload_to=users.models.upload_loction),
        ),
    ]
