# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 23:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0069_auto_20170421_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rounds',
            name='club',
        ),
        migrations.RemoveField(
            model_name='rounds',
            name='event',
        ),
    ]
