# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 23:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0070_auto_20170421_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='rounds',
            name='created',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
