# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0071_rounds_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='rounds',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
