# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 16:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0072_rounds_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_registered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registered', to=settings.AUTH_USER_MODEL)),
                ('registered_to', models.ManyToManyField(to='users.events')),
            ],
        ),
    ]
