# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 23:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0074_round_scores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round_scores',
            name='round',
        ),
        migrations.RemoveField(
            model_name='round_scores',
            name='student',
        ),
        migrations.DeleteModel(
            name='round_scores',
        ),
    ]
