# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0077_auto_20170426_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='round_scores',
            name='data1',
            field=models.FileField(null=True, upload_to=users.models.upload_loction),
        ),
        migrations.AddField(
            model_name='round_scores',
            name='data2',
            field=models.FileField(null=True, upload_to=users.models.upload_loction),
        ),
        migrations.AddField(
            model_name='round_scores',
            name='data3',
            field=models.FileField(null=True, upload_to=users.models.upload_loction),
        ),
    ]
