# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0078_auto_20170426_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='college',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='clubs',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
